// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzqWsLHKEcuvn4ZPux9DLLiync338-IiI',
    appId: '1:1034750484450:web:414b248d4b1b4a7b26e3bb',
    messagingSenderId: '1034750484450',
    projectId: 'scipro-362508',
    authDomain: 'scipro-362508.firebaseapp.com',
    storageBucket: 'scipro-362508.appspot.com',
    measurementId: 'G-7R6H5L464B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp1hFfdPKAEEN8TkskNPMHQ4gg6t5He5Y',
    appId: '1:1034750484450:android:a39c4b55b336d22d26e3bb',
    messagingSenderId: '1034750484450',
    projectId: 'scipro-362508',
    storageBucket: 'scipro-362508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwlfFLI2TwOZj3ZZhpSgBvsSmJCN8PQ3Q',
    appId: '1:1034750484450:ios:7628d3187eb2b69a26e3bb',
    messagingSenderId: '1034750484450',
    projectId: 'scipro-362508',
    storageBucket: 'scipro-362508.appspot.com',
    androidClientId: '1034750484450-0b2t2ti2famul8iemq9cdqia9pvejvln.apps.googleusercontent.com',
    iosClientId: '1034750484450-tp3n3epqub46r6labs1ob5nokae3rdrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sciproApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwlfFLI2TwOZj3ZZhpSgBvsSmJCN8PQ3Q',
    appId: '1:1034750484450:ios:7628d3187eb2b69a26e3bb',
    messagingSenderId: '1034750484450',
    projectId: 'scipro-362508',
    storageBucket: 'scipro-362508.appspot.com',
    androidClientId: '1034750484450-0b2t2ti2famul8iemq9cdqia9pvejvln.apps.googleusercontent.com',
    iosClientId: '1034750484450-tp3n3epqub46r6labs1ob5nokae3rdrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sciproApplication',
  );
}
